name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
        env:
          KEY: ${{ secrets.IWA_KEY }}
          KEY_PASSPHRASE: ${{ secrets.IWA_KEY_PASSPHRASE }}

      - name: Upload IWA Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iwa_bundle
          path: dist/iwa.swbn
          overwrite: true