name: Release

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    if: github.event_name == 'workflow_dispatch' || (github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Generate tag and changelog
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor

      - name: Get all tags
        uses: octokit/request-action@v2.x
        id: get_all_tags
        with:
          route: GET /repos/${{ github.repository }}/git/matching-refs/tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump IWA version and create update_manifest.json
        run: pnpm run bump
        env:
          VERSION: ${{ steps.tag_version.outputs.new_tag }}
          ALL_TAGS_JSON: ${{ steps.get_all_tags.outputs.data }}

      - name: Build IWA 
        id: build_iwa
        run: pnpm run build
        env:
          KEY: ${{ secrets.IWA_KEY }}
          KEY_PASSPHRASE: ${{ secrets.IWA_KEY_PASSPHRASE }}

      - name: Generate Release Body
        id: generate_release_body
        run: |
          EXTENSION_NAME=$(jq -r '.name' packages/extension/dist/manifest.json)
          CHANGELOG="${{ steps.tag_version.outputs.changelog }}"

          # Use a unique delimiter for multiline content
          EOF_MARKER=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 16)
          echo "body<<$EOF_MARKER" >> "$GITHUB_OUTPUT"
          echo "$CHANGELOG" >> "$GITHUB_OUTPUT"
          echo "" >> "$GITHUB_OUTPUT"
          echo "---" >> "$GITHUB_OUTPUT"
          echo "### Artifact IDs" >> "$GITHUB_OUTPUT"       
          echo "- **IWA Bundle ID:** \`${{ steps.build_iwa.outputs.iwa_url }}\`" >> "$GITHUB_OUTPUT"
          echo "$EOF_MARKER" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.generate_release_body.outputs.body }}
          artifacts: |
            dist/iwa.swbn
            ./update_manifest.json
